spring.application.name=agenda

spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_oficina
spring.datasource.username=postgres
spring.datasource.password=1108

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9091
server.address=0.0.0.0